return {
  { "ajmwagar/vim-deus" , lazy = false },
  { "arzg/vim-corvine" , lazy = false },
  { "chriskempson/vim-tomorrow-theme" , lazy = false },
  { "dracula/vim" , lazy = false },
  { "edeneast/nightfox.nvim" , lazy = false },
  { "hzchirs/vim-material" , lazy = false },
  { "jacoborus/tender.vim" , lazy = false },
  { "lifepillar/vim-gruvbox8" , lazy = false },
  { "lifepillar/vim-wwdc17-theme" , lazy = false },
  { "morhetz/gruvbox" , lazy = false },
  { "navarasu/onedark.nvim" , lazy = false },
  { "nlknguyen/papercolor-theme" , lazy = false },
  { "rakr/vim-one" , lazy = false },
  { "raphamorim/lucario" , lazy = false },
  { "rebelot/kanagawa.nvim" , lazy = false },
  { "rigellute/rigel" , lazy = false },
  { "rmehri01/onenord.nvim" , lazy = false },
  { "rose-pine/neovim" , lazy = false },
  { "sainnhe/everforest" , lazy = false },
  { "sainnhe/gruvbox-material" , lazy = false },
  { "luisiacc/gruvbox-baby" , lazy = false },
  { "sainnhe/sonokai" , lazy = false },
  { "savq/melange-nvim" , lazy = false },
  { "sonph/onehalf" , lazy = false },
  { "srcery-colors/srcery-vim" , lazy = false },
  { "tomasr/molokai" , lazy = false },
  { "zanglg/nova.vim" , lazy = false },
  { "rafi/awesome-vim-colorschemes" , lazy = false },
  { "rose-pine/neovim" , lazy = false },
  { "catppuccin/nvim", name = "catppuccin", lazy = false },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "onenord-light",
      -- colorscheme = "sonokai",
      -- colorscheme = "carbonfox",
      -- colorscheme = "catppuccin",
      -- colorscheme = "gruvbox-material",
      -- colorscheme = "onenord",
      -- colorscheme = "wwdc17",
      -- colorscheme = "OceanicNext",
    },
  },
}
