return {
  { "ajmwagar/vim-deus" },
  { "arzg/vim-corvine" },
  { "chriskempson/vim-tomorrow-theme" },
  { "dracula/vim" },
  { "edeneast/nightfox.nvim" },
  { "hzchirs/vim-material" },
  { "jacoborus/tender.vim" },
  { "lifepillar/vim-gruvbox8" },
  { "lifepillar/vim-wwdc17-theme" },
  { "morhetz/gruvbox" },
  { "navarasu/onedark.nvim" },
  { "nlknguyen/papercolor-theme" },
  { "rakr/vim-one" },
  { "raphamorim/lucario" },
  { "rebelot/kanagawa.nvim" },
  { "rigellute/rigel" },
  { "rmehri01/onenord.nvim" },
  { "rose-pine/neovim" },
  { "sainnhe/everforest" },
  { "sainnhe/gruvbox-material" },
  { "sainnhe/sonokai" },
  { "savq/melange-nvim" },
  { "sonph/onehalf" },
  { "srcery-colors/srcery-vim" },
  { "tomasr/molokai" },
  { "zanglg/nova.vim" },
  { "rafi/awesome-vim-colorschemes" },
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
  },

  -- {
  --   "LazyVim/LazyVim",
  --   opts = {
  --     -- colorscheme = "gruvbox-material",
  --     -- colorscheme = "onenord",
  --     colorscheme = "OceanicNext",
  --   },
  -- },
}
